Adding template to execute test container for performance Testing
argoproj-labs/argo-workflows-catalog pull request #17
Opened 2020-10-31 02:40 UTC by sumitnagal

This is well-proven solution we are using in Intuit, and we have not contributed back to open source, hence adding as part GED-2020 project.

2020-10-31 02:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj-labs/argo-workflows-catalog?pullRequest=17) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj-labs/argo-workflows-catalog?pullRequest=17) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj-labs/argo-workflows-catalog?pullRequest=17) it.</sub>

2020-10-31 16:37 UTC, alexec requested changes
Can you please run make to generate the HTML?

2020-10-31 16:37 UTC, alexec commented on templates/perf-infra/manifests.yaml
> +# Stress test to test upper bounds of concurrent pods
My only change is that everything should go into the manifest. Including any docs.

2020-11-02 06:46 UTC, sumitnagal commented
I am not able to make in hello template itself , let me know if I am missing anything 
![image](https://user-images.githubusercontent.com/2490216/97837989-24055980-1c94-11eb-9551-8a586d6c4045.png)

2020-11-02 15:31 UTC, alexec commented
You need to run `make` in the root directory of the project.

2020-11-02 18:22 UTC, sumitnagal commented
Added changes 
➜  argo-workflows-catalog git:(master) ✗ make
go run ./hack
templates/argocd-sync-and-wait/manifests.yaml
templates/buildkit/manifests.yaml
templates/distro/manifests.yaml
templates/go-build/manifests.yaml
templates/hello-world/manifests.yaml
templates/jenkins-pipeline/manifests.yaml
templates/sendmail/manifests.yaml
templates/slack/manifests.yaml
templates/terraform-basic/manifests.yaml

2020-11-02 18:39 UTC, sumitnagal commented
@alexec , please let me know

2020-11-02 18:39 UTC, alexec approved these changes

2020-11-02 18:39 UTC, merged